### ISSUE TITLE
Can't start the Handler

### ISSUE THREAD

**Issue by RedTeamWing** [SharpC2/SharpC2#1]
![image](https://user-images.githubusercontent.com/25416365/128545662-6902a798-de4e-4531-aa3a-05d43092fa5c.png)

the http server is seem down

**Comment by rasta-mouse** [comment]
Make sure that:

1. Port 80 is not already bound.
2. You have privs to bind to a low port (probably need to run the Team Server as a local admin).

You can also try using a high port like 8080 that shouldn't require elevated privs to listen on.

**Comment by j0nh4t** [comment]
I'm having a similar issue. Drone will not call back.

```
sudo dotnet bin/Debug/net5.0/TeamServer.dll Passw0rd!
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://0.0.0.0:8443
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /home/attacker/tools/SharpC2/TeamServer
```
	  
Client connects I see this debug in teamserver being spammed:

```
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
info: TeamServer.Authentication.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
info: TeamServer.Authentication.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
info: TeamServer.Authentication.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
info: TeamServer.Authentication.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
info: TeamServer.Authentication.BasicAuthenticationHandler[7]
      BasicAuthentication was not authenticated. Failure message: Missing Authorization Header
```


Creating handler:

```
[handlers] # list
Name          Running
----          -------
default-http  False
[handlers] # config default-http
[default-http] # set BindPort 9001
[default-http] # set ConnectPort 9001
[default-http] # set ConnectAddress 192.168.198.137
[default-http] # start
[default-http] # back                                                                                               
[handlers] # list
Name          Running
----          -------
default-http  True
```

Causes error:
```

crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.IO.IOException: Failed to bind to address https://0.0.0.0:8443: address already in use.
       ---> Microsoft.AspNetCore.Connections.AddressInUseException: Address already in use
       ---> System.Net.Sockets.SocketException (98): Address already in use
         at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
         at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
         at System.Net.Sockets.Socket.Bind(EndPoint localEP)
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
         at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
```
Odd that it tries to bind to 8443

```
[drones] # handlers
[handlers] # payload default-http exe /tmp/payload.exe
[+] Saved 74240 bytes.
```

drone.exe starts fine. I see it beaconing to the ip port configured but:

![image](https://user-images.githubusercontent.com/18689649/128562884-e80fa75b-99cc-4f2d-a4af-55d5600ec9e1.png)


```
[drones] # list

[drones] # 
```

Using latest Kali build

**Comment by rasta-mouse** [comment]
@j0nh4t I can replicate this issue, I'll look into it.
