### ISSUE TITLE
Unhandled exception. System.Text.Json.JsonException: The input does not contain any JSON tokens.

### ISSUE THREAD

**Issue by johnjohnsp1** [SharpC2/SharpC2#18]
getting this errore once typed generate <output path file>

[default-http] # show
Name            Value      Optional
----            -----      --------
BindPort        80         False
ConnectAddress  localhost  False
ConnectPort     80         False
[default-http] # start
[default-http] # [+] Handler "default-http" started.

[default-http] # back
[handlers] # back
[drones] # payloads
[payloads] # show
Handler  Format
-------  ------
         Exe
[payloads] # set handler default-http
[payloads] # generate c:\temp\ol.exe
Unhandled exception. System.Text.Json.JsonException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at SharpC2.Services.ApiService.GeneratePayload(Payload payload) in C:\temp\sharpc2\Client\Services\ApiService.cs:line 100
   at SharpC2.Screens.PayloadsScreen.GeneratePayload(String[] args) in C:\temp\sharpc2\Client\Screens\PayloadsScreen.cs:line 56
   at SharpC2.Screens.Screen.Show() in C:\temp\sharpc2\Client\Screens\Screen.cs:line 48
   at SharpC2.Screens.DroneScreen.OpenPayloadsScreen(String[] args) in C:\temp\sharpc2\Client\Screens\Drones\DroneScreen.cs:line 78
   at SharpC2.Screens.Screen.Show() in C:\temp\sharpc2\Client\Screens\Screen.cs:line 48
   at SharpC2.Program.Main(String[] args) in C:\temp\sharpc2\Client\Program.cs:line 72
   at SharpC2.Program.<Main>(String[] args)
PS C:\temp\sharpc2\Client\bin\Debug\net5.0>
PS C:\temp\sharpc2\Client\bin\Debug\net5.0>

this is the server side on error:

PS C:\temp\sharpc2\TeamServer\bin\Debug\net5.0> .\TeamServer.exe -p <random value>
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://0.0.0.0:8443
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\temp\sharpc2\TeamServer\bin\Debug\net5.0
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMBCI93MKQVQ", Request id "0HMBCI93MKQVQ:00000002": An unhandled exception was thrown by the application.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at TeamServer.Models.Payload.SetAppDomainName(ModuleDef module) in C:\temp\sharpc2\TeamServer\Models\Payloads\Payload.cs:line 91
         at TeamServer.Models.Payload.GetDroneModuleDef() in C:\temp\sharpc2\TeamServer\Models\Payloads\Payload.cs:line 32
         at TeamServer.Models.ExePayload.Generate() in C:\temp\sharpc2\TeamServer\Models\Payloads\ExePayload.cs:line 16
         at TeamServer.Controllers.PayloadsController.GetPayload(String handler, String format) in C:\temp\sharpc2\TeamServer\Controllers\PayloadsController.cs:line 52
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

no issue with dotnet build, both teamserver and client
i miss anything ?
thanks

**Comment by rasta-mouse** [comment]
Thanks @johnjohnsp1
